### ISSUE TITLE
Don't cache 'char' user

### ISSUE THREAD

**Issue by jomo** [jhead/Minecraft-Skin-Server#1]
"Char" is a valid username (as of today), you shouldn't cache it.

The Char skin looks like this:
[![char skin](https://crafatar.com/renders/body/Char?skin)](https://github.com/crafatar/crafatar)

**Comment by jhead** [comment]
Hey! Strange, I never got an email about this. Sorry about that. I'll drop "char" from the code and push a fix shortly.

**Comment by jhead** [comment]
Should be fixed as of bd6ee27
